### ISSUE TITLE
Make it work in the browser

### ISSUE THREAD

**Issue by torgeilo** [plasticrake/mocha-json-serialize-reporter#15]
Hi! Thanks for creating this. I'm running Mocha in remote browsers using Selenium WebDriver, and with this package and mocha-json-runner, I'm able to grab the Mocha report from the browser and replay it locally in the terminal. It's sweet, except that mocha-json-serialize-reporter depends on `require()`, `process.stdout.write()` and `module`, which don't exist in the browser. I've shimmed the necessary globals, but I'd love to drop those awful hacks and have mocha-json-serialize-reporter just work in the browser instead.

Would you be interested in such changes (or am I better off forking and making my own)?

I'm not too used to support both Node and the browser at the same time, but I'd be happy to submit a PR for further discussion if you're interested, and if I get my head around it (something like a browser entry point in package.json alongside main, where the main entry point interfaces with Node while the browser entry point is more browser friendly).

**Comment by plasticrake** [comment]
Yeah! I'm not too familiar with the best way to shim things to work in browser and node but I'm open to a PR for this.

**Comment by plasticrake** [comment]
Check out the pull request #20. `test/browser-test.html` has an example; it will output to browser console. If there is another way to you'd like to display (perhaps on the page) let me know.

**Comment by torgeilo** [comment]
Nice! Gave it a spin and it works great.

As you touch upon, I need a way to get the stringified JSON back to the computer which is controlling the remote test run. I can send/fetch the data if it's in a global or in an HTML element. It's not really important which one. 

The reporter could take a callback (if possible with the reporter options) or it could put the data somewhere. Maybe it's a good option to do something similar to the Mocha HTML reporter, to check for an element with a certain ID and set the text content of that element if it exists.

My current approach is to create a hidden HTML element when the test run completes, and let Selenium wait for the presence of that element. When it appears, another Selenium call is made to fetch the data, which I've stored inside the same HTML element.

I see Mocha recreates a few Node APIs in the browser, including process. I think it would be good to not set global.process, as it exposes Mocha's internal process shim to the rest of the browser, but it's up you.
