### ISSUE TITLE
Output empty (stdout)

### ISSUE THREAD

**Issue by adams-family** [plasticrake/mocha-json-serialize-reporter#24]
I was very happy to find this library, however unfortunately I don't seem to see any JSON output on `stdout`.

package.json: (snippet)
```
  "scripts": {
    "test": "NODE_ENV=TEST PORT=3500 mocha",
    "test-json": "NODE_ENV=TEST PORT=3500 mocha --reporter mocha-json-serialize-reporter"
  },
  "devDependencies": {
    "chai": "^4.3.4",
    "chai-http": "^4.3.0",
    "mocha": "^8.4.0",
    "mocha-json-serialize-reporter": "^1.4.0"
  }
```

Sample test:
```
const assert = require("assert");
const chai = require("chai");
const chaiHttp = require("chai-http");
const should = chai.should();
const server = require('../server');

chai.use(chaiHttp);

describe ("Healthcheck", function(){
    it("should return 200", done=>{
        chai.request(server)
            .get('/healthcheck')
            .end((err,res)=>{
                res.should.have.status(200);
                done();
            });
    });
});
```

`npm run test` works fine: outputs the application's console.logs + the test result at the end
`npm run test-json` outputs the applications console.logs but does not output any JSON, nor any error

Environment: docker image: `node:lts`

**Comment by plasticrake** [comment]
Does it work with the built-in mocha JSON reporter?

**Comment by adams-family** [comment]
Hmm, very interesting, this does nothing either:

`"NODE_ENV=TEST PORT=3500 mocha --reporter json"`

It only outputs the console.log-s from the application.

**Comment by plasticrake** [comment]
Well sounds like an environment setup on your end. I assume from running within docker? Doesn't seem related to this plugin

**Comment by adams-family** [comment]
Yes, running docker `node:latest` image. It's interesting that the default reporter works fine. I'll try to debug the default JSON reporter first.

**Comment by plasticrake** [comment]
This and the built in JSON just use `process.stdout.write`:
https://github.com/plasticrake/mocha-json-serialize-reporter/blob/7f4945a482a744c4089b82deb3bb62936d1c9c2a/lib/json-serialize-reporter.js#L299

**Comment by adams-family** [comment]
Ok, figured it out!

I had the following code in after() to exit `mocha` after all tests have finished:
```
after(() => {
    server.close()
    process.exit(0);
});
```

It causes prevents reporters except for `spec` from printing their result.

Adding a setTimeout to push process.exit into the next (deferred) event loop seems to fix the problem reliably:
```
after(() => {
    server.close()
    setTimeout(() => {
        process.exit(0);
    });
});
```
